# copied and edited from: https://github.com/ninadingole/docker-compose-stacks/blob/master/prometheus-grafana/docker-compose.yml

volumes:
  metdpg_prometheus_data: {}
  metdpg_grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus/
      - metdpg_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  blackbox-exporter:
    privileged: true
    build:
      context: .
      dockerfile: build/blackbox-exporter.Dockerfile
      pull: true
    image: blackbox-exporter-metdpg
    restart: always
    # cap_add:
    #   - NET_RAW
    # sysctls:
    #   net.ipv4.ping_group_range: "0 2147483647"
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/blackbox.yml'
      - '--log.level=debug'
    ports:
      - 9115:9115
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana
    user: '472'
    restart: always
    # environment:
    #   GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - metdpg_grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/etc/grafana/dashboards/
      - ./grafana/etc/grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - ./grafana/env.config
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus/
      - metdpg_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/alertmanager.yml'
    ports:
      - 9093:9093
    profiles: [alertmanager]

