modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      # headers:
      #   Host: vhost.example.com
      #   Accept-Language: en-US
      #   Origin: example.com
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: true
      fail_if_header_matches: # Verifies that no cookies are set
        - header: Set-Cookie
          allow_missing: true
          regexp: '.*'
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      ip_protocol_fallback: false  # no fallback to "ip6"
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      payload_size: 32
      preferred_ip_protocol: "ip4"
      ttl: 5
      dont_fragment: true
#      source_ip_address: "127.0.0.1"