global:
  scrape_interval: 1m
  scrape_timeout: 20s

# Alertmanager configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#       - targets:
#         - alertmanager:9093

# rule_files:
#   - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'web_probe'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
          - "web_targets.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
  - job_name: 'server_probe'
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
          - "server_targets.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['blackbox-exporter:9115']
